lib/webbkoll_web/router.ex
defmodule WebbkollWeb.Router do
  use WebbkollWeb, :router

  @default_locale Application.compile_env(:webbkoll, :default_locale)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :webbkoll do
    plug(WebbkollWeb.Plugs.MoreSecureHeaders)
    plug(WebbkollWeb.Plugs.Locale, @default_locale)
  end

  pipeline :api do
    plug(:accepts, ["json", "html"])
  end

  if Mix.env() == :dev do
    import Phoenix.LiveDashboard.Router

    scope "/api", WebbkollWeb do
      pipe_through(:api)

      post("/check", API.SiteController, :create)
      get("/check", API.SiteController, :show)
    end

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard"
    end
  end

  scope "/", WebbkollWeb do
    pipe_through([:browser, :webbkoll])

    get("/", PageController, :index)
  end

  scope "/:locale", WebbkollWeb do
    pipe_through([:browser, :webbkoll])

    post("/check", SiteController, :create)
    get("/check", SiteController, :redirect_to_index)
    get("/status", SiteController, :status)
    get("/results", SiteController, :results)

    get("/news", PageController, :news)
    get("/faq", PageController, :faq)
    get("/about", PageController, :about)
    get("/donate", PageController, :donate)

    get("/", PageController, :index)
  end
end

web/router.ex
defmodule Webbkoll.Router do
  use Webbkoll.Web, :router
  @default_locale Application.get_env(:webbkoll, :default_locale)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Webbkoll.MoreSecureHeaders
    plug Webbkoll.Locale, @default_locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Webbkoll do
    pipe_through :browser

    get "/", SiteController, :index
  end

  scope "/:locale", Webbkoll do
    pipe_through :browser # Use the default browser stack

    get "/about", SiteController, :about
    get "/tech", SiteController, :tech
    get "/check",  SiteController, :check
    get "/status", SiteController, :status
    get "/results", SiteController, :results

    get "/", SiteController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Webbkoll do
  #   pipe_through :api
  # end
end

lib/webbkoll_web/templates/page/about.html.eex
<article class="text">
  <h2><%= gettext "About" %></h2>
  <p><%= gettext "Webbkoll monitors privacy-enhancing features on websites, and helps you find out who is letting you exercise control over your privacy. We check to what extent a website monitors your behaviour and how much they gossip about the monitoring to third parties, based on what can be observed when visiting a given page. We’ve also compiled a set of recommendations for how to not track or gossip in digital environments." %></p>

  <h3 id="how"><%= gettext "How it works" %></h3>

  <p><%= gettext(~s|Webbkoll attempts to simulate what happens when a user visits a page with a typical browser without interacting with anything. The specified page is visited with <a href="https://www.chromium.org/">Chromium</a>, the browser that Google Chrome is based on; i.e., a typical end-user browser. Data (requests/responses, cookies, etc.) is collected, analyzed and presented. The browser has no addons/extensions installed, and Do Not Track (DNT) is not enabled (since this is the default setting in most browsers). Nothing is clicked, no consent is given.|) |> raw() %></p>

  <h3 id="limitations"><%= gettext "Limitations" %></h3>
  <p><%= gettext(~s|Webbkoll can only observe what happens when visiting a single page. It cannot tell you how the website is doing as a whole, how data is stored internally, what parties the data might be shared with, if the privacy policy is adequate, how the internal procedures are, and so on and so forth. A "good" Webbkoll result doesn't mean that everything is well (but a "bad" result certainly means that not all is well).|) %></p>

  <p><%= gettext(~s|This tool is primarly meant to be used as a starting point for web developers. It can only help with one piece of the puzzle.|) %></p>

  <h3 id="authors"><%= gettext "Authors and tech" %></h3>
  <p><%= gettext(~s|Webbkoll is developed by <a href="https://anders.unix.se/">Anders Jensen-Urstad</a> (programming, design) and <a href="https://twitter.com/teirdes">Amelia Andersdotter</a> (FAQ, legislative information) of <a href="https://dataskydd.net/">Dataskydd.net</a>, a Swedish non-governmental organization working on making data protection easy in law and in practice. We are not affiliated with any political party.|) |> raw() %></p>

  <p><%= gettext(~s|Webbkoll uses <a href="http://www.phoenixframework.org/">Phoenix Framework</a> (Elixir), <a href="https://github.com/GoogleChrome/puppeteer">Puppeteer</a> and numerous open source libraries; <a href="https://github.com/andersju/webbkoll#credits--licenses">see here</a> for specifics.|) |> raw %></p>

  <p><%= gettext(~s|We don't provide an API as we have limited resources, but <a href="https://github.com/andersju/webbkoll">the code is available</a> under the MIT license. See also the options below.|) |> raw %></p>

  <p><%= gettext(~s|The initial development of Webbkoll was funded by <a href="https://www.internetfonden.se">Internetfonden</a> / <a href="https://www.iis.se">IIS</a> in 2016. In late 2018 we received a small grant from <a href="https://digitalrights.fund/">Digital Rights Fund</a>. Other than that, we maintain this tool in our spare time. You can <a href="%{donate}">support our work</a>, if you wish.|, donate: Routes.page_path(@conn, :donate, @conn.assigns.locale)) |> raw() %></p>

  <h4><%= gettext "Translations" %></h4>
  <ul class="default">
    <li><%= gettext("German:") %> <a href="https://jakobssystems.net">Tomas Jakobs</a></li>
    <li><%= gettext("Norwegian:") %> <a href="https://efn.no/en/home/team#Blenning">Tom Fredrik Blenning</a> - <a href="https://efn.no">Elektronisk Forpost Norge</a></li>
  </ul>

  <h3 id="alternatives"><%= gettext "Alternatives and resources" %></h3>
  <p><%= gettext(~s|The only other similar service that we are aware of <em>that uses a real browser for testing</em> is <a href="https://privacyscore.org/">PrivacyScore</a> (open source). It does many of the same checks as Webbkoll, but additionally also checks e.g. TLS, and lets you create a list of sites to check (and rank).|) |> raw() %></p>

  <p><%= gettext(~s|For more rigorous and systematic testing we recommend that you check out <a href="https://github.com/mozilla/OpenWPM">OpenWPM</a>, which can be (and is) used to conduct large-scale studies.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://observatory.mozilla.org/">Observatory by Mozilla</a> (open source) analyzes CSP, HSTS, TLS and various other things (some of the Webbkoll tests are based on code from Observatory). See also <a href="https://csp-evaluator.withgoogle.com/">Google's CSP Evaluator</a>.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://www.hardenize.com/">Hardenize</a> is similar to Observatory, but also checks a domain's mail servers.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://report-uri.com/home/tools">Report URI</a> has many useful tools: CSP analyzer/builder, header analyzer (<a href="https://securityheaders.com/">securityheaders.com</a>), SRI hash generator, etc.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://www.ssllabs.com/ssltest/">Qualys SSL Server Test</a> is an excellent tool for analyzing a server's TLS/SSL configuration. <a href="https://testssl.sh/">testssl.sh</a> is an open source alternative.|) |> raw() %></p>

  <p><%= gettext(~s|See also <a href="https://infosec-handbook.eu/blog/online-assessment-tools/">Pros and cons of online assessment tools for web server security</a> from InfoSec Handbook (a site that also has many other relevant articles).|) |> raw() %></p>
</article>

lib/webbkoll_web/templates/page/about.html.heex
<article class="text">
  <h2><%= gettext "About" %></h2>
  <p><%= gettext "Webbkoll monitors privacy-enhancing features on websites, and helps you find out who is letting you exercise control over your privacy. We check to what extent a website monitors your behaviour and how much they gossip about the monitoring to third parties, based on what can be observed when visiting a given page. We’ve also compiled a set of recommendations for how to not track or gossip in digital environments." %></p>

  <h3 id="how"><%= gettext "How it works" %></h3>

  <p><%= gettext(~s|Webbkoll attempts to simulate what happens when a user visits a page with a typical browser without interacting with anything. The specified page is visited with <a href="https://www.chromium.org/">Chromium</a>, the browser that Google Chrome is based on; i.e., a typical end-user browser. Data (requests/responses, cookies, etc.) is collected, analyzed and presented. The browser has no addons/extensions installed, and Do Not Track (DNT) is not enabled (since this is the default setting in most browsers). Nothing is clicked, no consent is given.|) |> raw() %></p>

  <h3 id="limitations"><%= gettext "Limitations" %></h3>
  <p><%= gettext(~s|Webbkoll can only observe what happens when visiting a single page. It cannot tell you how the website is doing as a whole, how data is stored internally, what parties the data might be shared with, if the privacy policy is adequate, how the internal procedures are, and so on and so forth. A "good" Webbkoll result doesn't mean that everything is well (but a "bad" result certainly means that not all is well).|) %></p>

  <p><%= gettext(~s|This tool is primarly meant to be used as a starting point for web developers. It can only help with one piece of the puzzle.|) %></p>

  <h3 id="authors"><%= gettext "Authors and tech" %></h3>
  <p><%= gettext(~s|Webbkoll is developed by <a href="https://anders.unix.se/">Anders Jensen-Urstad</a> (programming, design) and <a href="https://twitter.com/teirdes">Amelia Andersdotter</a> (FAQ, legislative information) of <a href="https://dataskydd.net/">Dataskydd.net</a>, a Swedish non-governmental organization working on making data protection easy in law and in practice. We are not affiliated with any political party.|) |> raw() %></p>

  <p><%= gettext(~s|Webbkoll uses <a href="http://www.phoenixframework.org/">Phoenix Framework</a> (Elixir), <a href="https://github.com/GoogleChrome/puppeteer">Puppeteer</a> and numerous open source libraries; <a href="https://github.com/andersju/webbkoll#credits--licenses">see here</a> for specifics.|) |> raw %></p>

  <p><%= gettext(~s|We don't provide an API as we have limited resources, but <a href="https://github.com/andersju/webbkoll">the code is available</a> under the MIT license. See also the options below.|) |> raw %></p>

  <p><%= gettext(~s|The initial development of Webbkoll was funded by <a href="https://www.internetfonden.se">Internetfonden</a> / <a href="https://www.iis.se">IIS</a> in 2016. In late 2018 we received a small grant from <a href="https://digitalrights.fund/">Digital Rights Fund</a>. Other than that, we maintain this tool in our spare time. You can <a href="%{donate}">support our work</a>, if you wish.|, donate: Routes.page_path(@conn, :donate, @conn.assigns.locale)) |> raw() %></p>

  <h4><%= gettext "Translations" %></h4>
  <ul class="default">
    <li><%= gettext("German:") %> <a href="https://jakobssystems.net">Tomas Jakobs</a></li>
    <li><%= gettext("Norwegian:") %> <a href="https://efn.no/en/home/team#Blenning">Tom Fredrik Blenning</a> - <a href="https://efn.no">Elektronisk Forpost Norge</a></li>
  </ul>

  <h3 id="alternatives"><%= gettext "Alternatives and resources" %></h3>
  <p><%= gettext(~s|The only other similar service that we are aware of <em>that uses a real browser for testing</em> is <a href="https://privacyscore.org/">PrivacyScore</a> (open source). It does many of the same checks as Webbkoll, but additionally also checks e.g. TLS, and lets you create a list of sites to check (and rank).|) |> raw() %></p>

  <p><%= gettext(~s|For more rigorous and systematic testing we recommend that you check out <a href="https://github.com/mozilla/OpenWPM">OpenWPM</a>, which can be (and is) used to conduct large-scale studies.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://observatory.mozilla.org/">Observatory by Mozilla</a> (open source) analyzes CSP, HSTS, TLS and various other things (some of the Webbkoll tests are based on code from Observatory). See also <a href="https://csp-evaluator.withgoogle.com/">Google's CSP Evaluator</a>.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://www.hardenize.com/">Hardenize</a> is similar to Observatory, but also checks a domain's mail servers.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://report-uri.com/home/tools">Report URI</a> has many useful tools: CSP analyzer/builder, header analyzer (<a href="https://securityheaders.com/">securityheaders.com</a>), SRI hash generator, etc.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://www.ssllabs.com/ssltest/">Qualys SSL Server Test</a> is an excellent tool for analyzing a server's TLS/SSL configuration. <a href="https://testssl.sh/">testssl.sh</a> is an open source alternative.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://internet.nl/">Internet.nl</a> checks HTTPS/TLS, DNSSEC, headers, etc.|) |> raw() %></p>

  <p><%= gettext(~s|<a href="https://check-your-website.server-daten.de/">check-your-website</a> checks HTTPS/TLS, DNSSEC, headers, cookies, content, etc.|) |> raw() %></p>
</article>

lib/webbkoll_web/templates/page/donate.html.eex
<article class="text">
  <h2><%= gettext "Donate" %></h2>

  <p><%= gettext(~s|Webbkoll is a project by <a href="https://dataskydd.net/">Dataskydd.net Sverige</a>, a Swedish non-governmental organization (organization number 802495-4797) working on making data protection easy in law and in practice. We are not affiliated with any political party.|) |> raw %></p>

  <p><%= gettext "We operate on a very small budget, and servers are usually our main expense; most work is done in our free time. Every euro (or krona) counts!" %></p>

  <p><%= gettext("<strong>If you would like to make a contribution</strong> to the general funds of Dataskydd.net (helping both Webbkoll as well as our other activities), you can transfer money to the following bank account:") |> raw() %></p>

  <ul>
    <li>Bank: SEB (Skandinaviska Enskilda Banken)</li>
    <li>BIC/SWIFT: ESSESESS</li>
    <li>IBAN: SE2150000000052031057715</li>
  </ul>

  <p><%= gettext "Please write \"Donation\" in the message field. Any amount is much appreciated! (From a Swedish bank account, the number would be 52031057715.)" %></p>

  <p><%= gettext "Our address (if necessary):" %></p>

  <p>
    Dataskydd.net Sverige<br>
    c/o Jensen-Urstad<br>
    Bondegatan 64<br>
    11633 Stockholm<br>
    Sweden
  </p>

  <p><%= gettext "Our bank's address (if necessary):" %></p>
  <p>
    SEB<br>
    106 40 Stockholm<br>
    Sweden
  </p>

  <p><%= gettext "At the moment we cannot accept Bitcoin or any other cryptocurrency." %></p>
</article>

lib/webbkoll_web/templates/page/donate.html.heex
<article class="text">
  <h2><%= gettext "Donate" %></h2>

  <p><%= gettext(~s|Webbkoll is a project by <a href="https://dataskydd.net/">Dataskydd.net Sverige</a>, a Swedish non-governmental organization (organization number 802495-4797) working on making data protection easy in law and in practice. We are not affiliated with any political party.|) |> raw %></p>

  <p><%= gettext "We operate on a very small budget, and servers are usually our main expense; most work is done in our free time. Every euro (or krona) counts!" %></p>

  <p><%= gettext("<strong>If you would like to make a contribution</strong> to the general funds of Dataskydd.net (helping both Webbkoll as well as our other activities), you can transfer money to the following bank account:") |> raw() %></p>

  <ul>
    <li>Bank: SEB (Skandinaviska Enskilda Banken)</li>
    <li>BIC/SWIFT: ESSESESS</li>
    <li>IBAN: SE2150000000052031057715</li>
  </ul>

  <p><%= gettext "Please write \"Donation\" in the message field. Any amount is much appreciated! (From a Swedish bank account, the number would be 52031057715.)" %></p>

  <p><%= gettext "Our address (if necessary):" %></p>

  <p>
    Dataskydd.net Sverige<br>
    c/o Jensen-Urstad<br>
    Bondegatan 64<br>
    11633 Stockholm<br>
    Sweden
  </p>

  <p><%= gettext "Our bank's address (if necessary):" %></p>
  <p>
    SEB<br>
    106 40 Stockholm<br>
    Sweden
  </p>

  <p><%= gettext "At the moment we cannot accept Bitcoin or any other cryptocurrency." %></p>
</article>

lib/webbkoll_web/templates/page/faq.html.eex
<article class="text">
  <h2><%= gettext "FAQ" %></h2>

  <h3><%= gettext "What is data protection?" %></h3>

  <p><%= gettext "Data protection is a human right in the European Union. It’s a collection of administrative and formal requirements for how to collect, process and use data relating to individuals. The purpose of this protection is to provide individuals with the means necessary to exercise their right to privacy. Data protection law guarantees transparency, choice and knowledge for individuals with regards to who influences them, and under which conditions." %></p>

  <p><%= gettext "In May 2018 a new law about data protection will enter into force in the European Union. It is a regulation and will apply equally in all the 28 member states." %></p>

  <h3><%= gettext "What is ”behavioural monitoring”?" %></h3>

  <p><%= gettext "Behavioural monitoring, or ”profiling”, is when someone monitors how a given person, or set of persons, typically behave. This includes monitoring whether a particular group, say young people or women of a median income, frequently visit certain deeplinks, have to look up certain vocabulary or that they end up on the website through using a particular search engine or social platform. Behavioural monitoring is used to discover what certain classes of people may be assumed to find interesting, difficult or funny." %></p>

  <p><%= gettext "It is also the categorisation of individuals into these groups. Once a web visitor is stuffed into a particular category, they may be positively or negatively discriminated against because of the categorisation." %></p>

  <p><%= gettext "Profiling is mostly used in the advertisement industry to decide which type of advertisements a particular individual should be exposed to. Parents of small children, or people who know parents of small children, may receive ads for nappies, prams or family vacations. Increasingly, profiling is used to determine what contents are served by newspapers. The above mentioned groups may for instance receive short articles about new-borns if they are queueing (and have little time) or longer articles about new-borns if they are on a train (and have more time)." %></p>

  <p><%= gettext "Profiling may additionally be used to shape political opinions, for instance through targeting specific groups with political information, or to enact measures against groups based on their assumed characteristics. This form of political work is called ”nudging” and may also be deployed to increase acceptance of specific measures (like the construction of a public park) in specific groups (such as the individuals living near the envisaged park)." %></p>

  <h3><%= gettext "What do you mean by ”gossiping to third-parties”?" %></h3>

  <p><%= gettext "We use the word gossiping to mean that information about somebody’s behaviour, reading habits or preferences is handed over to somebody other than the actor responsible for the website." %></p>

  <p><%= gettext "In modern web development, it’s become common for a website not to be run from only one location. When you visit a website, you’re not only entering into contact with those running the website, but also all the businesses and organisations which collaborate with the managers of the websites. These may be internet service providers, script providers, font providers, analytics tools providers and a range of other providers. If the manager of the websites hands over information about visitors to any of these third-parties, it is a form of gossiping since it is usually not evident to the visitors that this type of information is being handed over." %></p>

  <p><%= gettext "A webstore may for instance hand over the task of profiling visitors to an advertisement agency, and a public authority may have constructed its website in a way that automatically hands over behavioural data to advertisers. Advertisers are the most common and least transparent form of third parties." %></p>

  <h3><%= gettext "What are the principles of the EU general data protection regulation?" %></h3>

  <p><%= gettext(~s|The <a href="http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679">general data protection regulation of the European Union</a> enters into force on the 25th of May 2018 and concerns the balancing of power being those influencing individuals (typically companies and public authorities) and the individuals themselves. Webbkoll is a tool to find out who is collecting information about individuals, and what can be done to stop invisible tracking.|) |> raw %></p>

  <h4><%= gettext "Lawfulness, fairness and transparency" %></h4>
  <p><%= gettext "An individual should be able to understand the terms under which their data is being processed (by others). (5(1)(a))." %></p>

  <p><%= gettext "Webbkoll sees lawfulness, fairness and transparency as a requirement that individuals should understand with whom they are in contact by visiting a website. If an advertisement agency or some other company, such as an internet service provider, has easy access to behavioural data the individual should know. If an individual may be influenced by these parties, again they should be able to know. An individual should not have to master web development or have a need for advanced technical tools to find this out. While the principle of transparency is simple, permissible deviations from transparency are listed in articles 13-20 of the regulation." %></p>

  <p><%= gettext "Transparency also means a right to find out when something gone wrong: if you’ve collected information about individuals which have leaked or disappeared, the individual has a right to know. This is called ”personal data breach notification” and specific rules are in article 34 of the regulation." %></p>

  <h4><%= gettext "Purpose limitation" %></h4>
  <p><%= gettext "Data collection should occur only for specific and limited purposes. These purposes should be explicit and understandable. (5(1)(b))" %></p>

  <p><%= gettext "The purpose for collecting data may be interpreted broadly, and means anything from marketing to improving the web. At Dataskydd.net's Webbkoll we prefer methods of improving the web that do not include collecting data from private persons. That’s why we’ve compiled a large number of recommendations and tools which minimise data collection." %></p>

  <h4><%= gettext "Data minimisation" %></h4>
  <p><%= gettext "As little data as possible to achieve the purpose should be collected .(5(1)(c))" %></p>

  <p><%= gettext "Depending on the purposes for collecting personal data, data minimisation may mean different things. Webbkoll makes it easy to find out how not to collect personal data and how not to inadvertently leak personal data. Should one want to collect personal data anyway, one needs to be transparent about such collection and one also needs to follow the rules in chapter 4 of the regulation. The rules of how to collect and process personal data are in place to ensure that anyone who chooses a purpose for data collection also reflects on the consequences of such choices." %></p>

  <h4><%= gettext "Accuracy" %></h4>
  <p><%= gettext "Personal data shall be accurate, and if they aren’t, there must be a procedure to correct them." %></p>

  <p><%= gettext "This principle above all concerns information registered by public authorities or companies, for instance in the credit check industry. In web development, it is more common with ”fuzzy” data sets, and the consequences of being erroneously categorised in a given profiling operation is normally not worse than that one receives online advertisement which is not specifically targeted to ones own group." %></p>

  <h4><%= gettext "Storage limitation" %></h4>
  <p><%= gettext "Personal data should not be saved or stored longer than necessary." %></p>

  <p><%= gettext "This right ties into purpose limitation and data minisation. If one follows the recommendation of Webbkoll, one does not have to concern oneself so much with this principle." %></p>

  <h4><%= gettext "Integrity and confidentiality" %></h4>
  <p><%= gettext "Data should be processed in a secure way, both organisatorially and technically." %></p>

  <p><%= gettext "Webbkoll makes it easy to see which technical protection mechanisms for data protection are in place in a given website. We have identified measures which should not require large organisational changes, or increase web management costs. Most of our recommendations are simple enough to implement, and they are cost neutral. Our goal is to make it as easy as possible for individuals to exercise their rights to privacy and data protection, and also to provide web designers and managers with simple ”rules of thumb” to help individuals exercise these rights." %></p>

  <h4><%= gettext "Accountability" %></h4>
  <p><%= gettext "The one responsible for the website is responsible for adherence to these principles." %></p>

  <p><%= gettext "Since responsibility can be a difficult burden, Webbkoll has a large set of recommendations for data protection which may go further than what one could be legally liable for. We want to enable the best possible data protection with the least amount of administrative burdens. One of the reasons the rules of the data protection regulation make it seem bureaucratic and boring not to data minimise, is so that each actor in society who wishes to influence others has to consider carefully the way in which they use such power." %></p>
</article>

lib/webbkoll_web/templates/page/index.html.eex
<div class="index-search">
  <section>

    <%= if @conn.assigns.locale == "en" do %>
    <div class="flash-notice">
      <p>
        <span class="icon-sphere"></span> Webbkoll is also available in <a href="/de/">German</a> (auf Deutsch), <a href="/no/">Norwegian</a> (norsk), <a href="/sv/">Swedish</a> (svenska) and <a href="/it/">Italian</a> (italiano)!
      </p>
    </div>
    <% end %>

    <h1><%= gettext "Check your site!" %></h1>

    <%= form_for @conn, Routes.site_path(@conn, :create, @conn.assigns.locale), [class: "search-bar"], fn f -> %>
      <%= text_input f, :url, [type: "search", required: "required", placeholder: "example.com", "aria-label": gettext("URL to check")] %>
      <%= submit gettext "Check" %>
    <% end %>

    <p class="desc">
      <%= gettext "This tool helps you check what data-protecting measures a site has taken to help you exercise control over your privacy." %>
    </p>

    <div class="notes">
      <%= if @check_host_only do %>
        <p><i class="icon-notification alert"></i> <%= gettext(~s|Due to abuse Webbkoll will, until further notice, throw away query parameters and path from the URL you enter; i.e., if you enter <code>http://example.com/foo/?bar=42</code>, <code>http://example.com</code> will be checked.|) |> raw() %></p>
      <% end %>
      <p><%= gettext(~s|Please note:|) %></p>
      <ol class="default">
        <li><%= gettext(~s|This tool simulates a normal browser visit with Do Not Track disabled (browser default) and with no add-ons.|) %></li>
        <li><%= gettext(~s|Even if you enter https://, http:// will be checked, to see if it redirects to https:// automatically (redirects are followed).|) %></li>
        <li><%= gettext(~s|Generally things work, but some sites (sometimes) don't work for various reasons.|) %></li>
        <li><%= gettext(~s|Feedback is appreciated: send <a href="mailto:info@dataskydd.net">email</a> or <a href="https://github.com/andersju/webbkoll">open an issue</a>.|) |> raw() %></li>
      </ol>
    </div>
  </section>
</div>

lib/webbkoll_web/templates/page/index.html.heex
<div class="index-search">
  <section>

    <%= if @conn.assigns.locale == "en" do %>
    <div class="flash-notice">
      <p>
        <span class="icon-sphere"></span> Webbkoll is also available in <a href="/de/">German</a> (auf Deutsch), <a href="/no/">Norwegian</a> (norsk), <a href="/sv/">Swedish</a> (svenska) and <a href="/it/">Italian</a> (italiano)!
      </p>
    </div>
    <% end %>

    <h1><%= gettext "Check your site!" %></h1>

    <%= form_for @conn, Routes.site_path(@conn, :create, @conn.assigns.locale), [class: "search-bar"], fn f -> %>
      <%= text_input f, :url, [type: "search", required: "required", placeholder: "example.com", "aria-label": gettext("URL to check")] %>
      <%= submit gettext "Check" %>
    <% end %>

    <p class="desc">
      <%= gettext "This tool helps you check what data-protecting measures a site has taken to help you exercise control over your privacy." %>
    </p>

    <div class="notes">
      <%= if @check_host_only do %>
        <p><i class="icon-notification alert"></i> <%= gettext(~s|Due to abuse Webbkoll will, until further notice, throw away query parameters and path from the URL you enter; i.e., if you enter <code>http://example.com/foo/?bar=42</code>, <code>http://example.com</code> will be checked.|) |> raw() %></p>
      <% end %>
      <p><%= gettext(~s|Please note:|) %></p>
      <ol class="default">
        <li><%= gettext(~s|This tool simulates a normal browser visit with Do Not Track disabled (browser default) and with no add-ons.|) %></li>
        <li><%= gettext(~s|Even if you enter https://, http:// will be checked, to see if it redirects to https:// automatically (redirects are followed).|) %></li>
        <li><%= gettext(~s|Generally things work, but some sites (sometimes) don't work for various reasons.|) %></li>
        <li><%= gettext(~s|Feedback is appreciated: send <a href="mailto:info@dataskydd.net">email</a> or <a href="https://github.com/andersju/webbkoll">open an issue</a>.|) |> raw() %></li>
      </ol>
    </div>
  </section>
</div>